name: sonya
description: Discord API library for Dart and Flutter with Riverpod cacheing.
version: 0.1.0
homepage: https://github.com/aoisensi/dart_sonya

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  riverpod: ^2.0.0-dev

dev_dependencies:
  build_runner: ^2.2.1
  dotenv: ^4.0.1
  flutter_lints: ^2.0.0
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  test: ^1.21.6
  total_lints: ^2.18.0
